-- tinh doanh so cua nhan vien theo tung thang trong nam 2017
SELECT
    EMPLOYEES.EMPLOYEE_ID, CONCAT(CONCAT(EMPLOYEES.FIRST_NAME, ' '), EMPLOYEES.LAST_NAME) AS FULL_NAME,
    SUM(ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE) TOTAL_REVENUE,
    TO_CHAR(ORDERS.ORDER_DATE, 'YYYY-MM') MONTH
FROM
    EMPLOYEES, ORDERS, ORDER_ITEMS, PRODUCTS
WHERE
    EXTRACT(YEAR FROM ORDERS.ORDER_DATE) = 2017
    AND UPPER(ORDERS.STATUS) = 'SHIPPED'
    AND EMPLOYEES.EMPLOYEE_ID = ORDERS.SALESMAN_ID
    AND ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID
    AND PRODUCTS.PRODUCT_ID = ORDER_ITEMS.PRODUCT_ID
GROUP BY
    TO_CHAR(ORDERS.ORDER_DATE, 'YYYY-MM'),
    EMPLOYEES.EMPLOYEE_ID, CONCAT(CONCAT(EMPLOYEES.FIRST_NAME, ' '), EMPLOYEES.LAST_NAME)
ORDER BY
    MONTH,
    TOTAL_REVENUE DESC
;


---------C2

SELECT DISTINCT
    EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME || ' ' ||EMPLOYEES.LAST_NAME AS FULL_NAME,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 1
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T1,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 2
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T2,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 3
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T3,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 4
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T4,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 5
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T5,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 6
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T6,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 7
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T7,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 8
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T8,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 9
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T9,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 10
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T10,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 11
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T11,
    SUM(
        CASE WHEN EXTRACT(MONTH FROM ORDERS.ORDER_DATE) = 12
        THEN ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE ELSE 0 END)
        AS T12
FROM
    EMPLOYEES ,ORDERS, ORDER_ITEMS, PRODUCTS
WHERE
    EXTRACT(YEAR FROM ORDERS.ORDER_DATE) = 2017
    AND UPPER(ORDERS.STATUS) = 'SHIPPED'
    AND EMPLOYEES.EMPLOYEE_ID = ORDERS.SALESMAN_ID
    AND ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID
    AND PRODUCTS.PRODUCT_ID = ORDER_ITEMS.PRODUCT_ID
GROUP BY
    EMPLOYEES.EMPLOYEE_ID, EMPLOYEES.FIRST_NAME || ' ' ||EMPLOYEES.LAST_NAME
;






-- thong ke doanh thu ban ra va hang ton kho cua cac san pham

WITH SHORT_INVENTORY AS (
    SELECT PRODUCT_ID, SUM(QUANTITY) AS IN_STOCK
    FROM INVENTORIES
    GROUP BY PRODUCT_ID
),
PRODUCT_ITEM AS (
    SELECT PRODUCT_ID, SUM(QUANTITY) TOTAL_QUANTITY
    FROM ORDER_ITEMS
    GROUP BY PRODUCT_ID
)
SELECT
    PRODUCTS.PRODUCT_ID,
    PRODUCTS.PRODUCT_NAME,
    NVL(PRODUCT_ITEM.TOTAL_QUANTITY * PRODUCTS.LIST_PRICE, 0) TOTAL_REVENUE,
    NVL(SHORT_INVENTORY.IN_STOCK, 0) IN_STOCK
FROM
    SHORT_INVENTORY, PRODUCT_ITEM, PRODUCTS
WHERE
    PRODUCT_ITEM.PRODUCT_ID(+) = PRODUCTS.PRODUCT_ID
    AND PRODUCTS.PRODUCT_ID = SHORT_INVENTORY.PRODUCT_ID(+)
ORDER BY
    TOTAL_REVENUE DESC,
    SHORT_INVENTORY.IN_STOCK
;





-- thong ke 10 khach hang tieu nhieu tien nhat 2017
SELECT
    CUSTOMERS.CUSTOMER_ID, CUSTOMERS.NAME, CUSTOMERS.ADDRESS, CUSTOMERS.CREDIT_LIMIT,
    SUM(ORDER_ITEMS.QUANTITY * PRODUCTS.LIST_PRICE) TOTAL_REVENUE
FROM
    CUSTOMERS, ORDERS, ORDER_ITEMS, PRODUCTS
WHERE
    CUSTOMERS.CUSTOMER_ID = ORDERS.CUSTOMER_ID
    AND ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID
    AND ORDER_ITEMS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
    AND EXTRACT(YEAR FROM ORDERS.ORDER_DATE) = 2017
    AND UPPER(ORDERS.STATUS) = 'SHIPPED'
GROUP BY
    CUSTOMERS.CUSTOMER_ID, 
    CUSTOMERS.NAME, 
    CUSTOMERS.ADDRESS, 
    CUSTOMERS.CREDIT_LIMIT
ORDER BY
    TOTAL_REVENUE DESC
    FETCH NEXT 10 ROWS WITH TIES
;